### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elPytel** [elPytel/Shell#6]
- [x] Jednotná složka pro instalace skriptů
   - /usr/local/bin, linky na programy
   - /usr/local/lib, knihovny
   - /usr/local/share, data programů
   - /usr/local/etc, konfigurace programů

- [ ] Vytvořit instalační scripty
   - seznam závislostí, jejichž existence se musí zkontrolovat
   - instalace chybějících závislostí?
- [ ] Github action work flow, testování
- [ ] Rozdělit repositář na jednotlivé programy a knihovny
- [ ] Jak zařídit, aby programy mohli spouštět další programy a vše šlo otestovat v GitHub actions?
